DEFAULT_OA_API_VERSION = "v1"
DEFAULT_3RDAPP_API_VERSION = "v2.0"
DEFAULT_OA_API_BASE = "https://openapi.zaloapp.com/oa"
USER_AGENT = "zalosdk/1.0 Zalo Open API Python SDK"
SDK_VERSION = "Python 1.0"
SDK_SOURCE = "PythonSDK-1.0"
MAXIMUM_FILE_SIZE = 5242880

DEFAULT_HEADER = {
    "User-Agent": USER_AGENT,
    "SDK_VERSION": SDK_VERSION,
    "SDK-Source": SDK_SOURCE
}
